version: "3.7"
services:
  laravel:
    user: nginx    
    build:      
      args:
        user: nginx
        uid: 994
      dockerfile: Dockerfile
      context: .
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 9000:9000
    secrets:
      - mysql_pass
      - mysql_user
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=database_name
      # uncomment these lines just for developement purpose
      # - DB_USERNAME=your_username
      # - DB_PASSWORD=your_pass
    volumes:
      - .:/var/www/html
    # networks:
    #   - proxy
secrets:
  mysql_pass:
    external: true
  mysql_user:
    external: true
# networks:
#   proxy:
#     external: true
      